name: Ce

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_tag: [fjtrujy/pspdev]

    container: ${{ matrix.docker_tag }}:latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y build-essential git bash cmake gcc-8 g++-8
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100

    - name: Compile project
      run: |
        cd ./psp
        make clean
        make -j$(nproc)  # Compile using all available CPU cores

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
    
    - name: Sanitized Docker Tag
      id: docker_tag
      run: echo "docker_tag=$(echo ${{ matrix.docker_tag }} | sed s:/:__:g)" >> $GITHUB_ENV

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: hello-${{ env.sha8 }}-${{ env.docker_tag }}
        path: ./psp/EBOOT.PBP
