name: Build NullDCe PSP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install essential dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential git wget

      - name: Set up PSPDEV environment variable
        run: |
          export PSPDEV=$HOME/pspdev
          export PATH=$PSPDEV/bin:$PATH
          mkdir -p $PSPDEV

      - name: Install PSP toolchain
        run: |
          git clone https://github.com/pspdev/psptoolchain.git
          cd psptoolchain
          ./toolchain.sh
        env:
          PSPDEV: $HOME/pspdev
          PATH: $HOME/pspdev/bin:$PATH

      - name: Configure build
        run: |
          export PSPDEV=$HOME/pspdev
          export PATH=$PSPDEV/bin:$PATH
          cd nulldce-psp
          cmake .

      - name: Build project
        run: |
          export PSPDEV=$HOME/pspdev
          export PATH=$PSPDEV/bin:$PATH
          cd nulldce-psp
          make

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: NullDCe-PSP-Build
          path: nulldce-psp/build/
