name: Build NullDCe PSP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential git wget

      - name: Set up PSPDEV environment variable
        run: |
          export PSPDEV=$HOME/pspdev
          export PATH=$PSPDEV/bin:$PATH
          mkdir -p $PSPDEV

      - name: Install PSP toolchain
        run: |
          git clone https://github.com/pspdev/psptoolchain.git
          cd psptoolchain
          ./toolchain.sh
        env:
          PSPDEV: ${{ runner.workspace }}/pspdev
          PATH: ${{ runner.workspace }}/pspdev/bin:$PATH

      - name: Clone NullDCe PSP repository
        run: |
          git clone https://github.com/PSP-Archive/nulldce-psp.git
          cd nulldce-psp

      - name: Configure build
        run: |
          export PSPDEV=${{ runner.workspace }}/pspdev
          export PATH=$PSPDEV/bin:$PATH
          cmake .

      - name: Build project
        run: |
          export PSPDEV=${{ runner.workspace }}/pspdev
          export PATH=$PSPDEV/bin:$PATH
          make

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: NullDCe-PSP-Build
          path: nulldce-psp/build/
